# Generated by Django 5.2.1 on 2025-05-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('In progess', 'In progess'), ('Done', 'Done')], default='Started', max_length=20)),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
