# Generated by Django 5.2.1 on 2025-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('In progress', 'In progress'), ('Done', 'Done')], default='Started', max_length=20),
        ),
    ]
